; ===========================================================================
; *                   S1HS - Hack configuration file                        *
; ===========================================================================
; This file is generated by S1HS to configure the hack.
; Note: this file is getting overriten every time you press Save button in
;	S1HS until you disable Tweaking in Options tab.
; ===========================================================================

_DEBUG_		equ 0

; Sonic Tweaking
_SPINDASH_	equ 1
_JUMPDASH_	equ 1
_SPEEDCAPFIX_	equ 1
_SPIKEBUGFIX_	equ 1


; Boss Hits
var_BHits_GHZ	= 8
var_BHits_MZ	= 8
var_BHits_SYZ	= 8
var_BHits_LZ	= 8
var_BHits_SLZ	= 8
var_BHits_FZ	= 8
